//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSS_test_task
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wage
    {
        public int Id { get; set; }
        public decimal Salary { get; set; }
        public System.DateTime Datetime { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
